version: '3'

services:
  web:
    build:
      context: ./ComicBookShopCoreWeb
      dockerfile: ./Dockerfile
    ports:
        - "4201:4200"
  db:
    build:
      context: ./ComicBookShopCore.Data/
      dockerfile: Dockerfile
    ports:
      - "1533:1433"
  webapi:
    build:
      context: ./
      dockerfile: ./ComicBookShopCore.WebAPI/Dockerfile
    ports:
      - "8081:80"
      - "8434:433"
    volumes:
    - /etc/ssl/certs/ssl-cert-snakeoil.pem:/app/fullchain.pem
    - /etc/ssl/private/ssl-cert-snakeoil.key:/app/privkey.pem
    depends_on:
      - db
