version: '3'

services:
  web:
    build:
      context: ./ComicBookShopCoreWeb
      dockerfile: ./Dockerfile
    ports:
      - "4201:4200"
    depends_on:
      - webapi
  db:
    build:
      context: ./ComicBookShopCore.Data/
      dockerfile: Dockerfile
    ports:
      - "1533:1433"
  webapi:
    build:
      context: ./
      dockerfile: ./ComicBookShopCore.WebAPI/Dockerfile
    ports:
      - "8081:80"
      - "8434:433"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
